buildWin:
	g++ -o ../bin/system.exe src/main.cpp src/../../../teenyat.c  -Ic:\dev\include\SDL2 -Ic:\dev\include -Lc:\dev\lib -lmingw32 -lSDL2main -lSDL2

buildLinux:
	g++ -o ../bin/system src/main.cpp src/../../../teenyat.c  -Ic:\dev\include\SDL2 -Ic:\dev\include -Lc:\dev\lib -lSDL2main -lSDL2